### ISSUE TITLE
After installation white screen

### ISSUE THREAD

**Issue by emre-bozkurt** [3x1io/vilt-admin#10]
I installed the project with the following installation instructions but my screen is empty white screen when i changed the routes like /login or /register nothing changed and no console error can you help me?

![image](https://user-images.githubusercontent.com/35993608/170222701-35f180e0-bb91-4ce1-a197-1245573292d7.png)

**Comment by 3x1io** [comment]
please use this tool to clear cache of the browser because the project is client-side rendering

[Web Developer](https://chrome.google.com/webstore/detail/web-developer/bfbameneiokkgbdmiekhjnmfkcnldhhm)

and check this [doc](https://github.com/3x1io/vilt-admin/wiki/Environment-Setup)
